@description('Azure region for all production resources.')
param location string = 'japaneast'

@description('First day of the Azure budget period.')
param budgetStartDate string = utcNow('yyyy-MM-01T00:00:00Z')

@description('Short resource prefix. Use lowercase letters and hyphens.')
@minLength(3)
@maxLength(18)
param namePrefix string = 'bifrost'

@description('Allowed browser origins for the public and admin API.')
param allowedOrigins array = [
  'https://cpower-2ng.github.io'
  'http://localhost:8000'
  'http://127.0.0.1:8000'
  'http://localhost:8123'
  'http://127.0.0.1:8123'
  'http://localhost:8124'
  'http://127.0.0.1:8124'
  'http://localhost:8125'
  'http://127.0.0.1:8125'
]

@description('GitHub owner/repository receiving synchronized content commits.')
param githubRepository string = 'cpower-2NG/cpower-2NG.github.io'

@description('Container image containing the Playwright QQ synchronizer.')
param syncImage string = 'ghcr.io/cpower-2ng/bifrost-qzone-sync:latest'

@description('Microsoft Entra tenant used by the administrator.')
param entraTenantId string

@description('Microsoft Entra SPA application client id.')
param entraClientId string

@description('API audience exposed by the Entra application.')
param entraApiAudience string

@description('Microsoft Entra object ids allowed to use the admin API.')
param adminObjectIds array

@description('GitHub App id used for short-lived repository installation tokens.')
param githubAppId string

@description('GitHub App installation id for the Pages repository.')
param githubAppInstallationId string

@description('Optional email addresses receiving Azure budget alerts.')
param budgetContactEmails array = []

@secure()
@description('GitHub App private key. Stored in Key Vault and never exposed to the browser.')
param githubAppPrivateKey string

@secure()
@description('Long random salt used for visitor and IP hashes.')
param hashSalt string

@description('Fallback admin account for password login. Empty disables the password channel.')
param adminUsername string = ''

@secure()
@description('scrypt hash for the fallback admin account, generated by tools/generate-admin-hash.mjs. Empty disables the password channel.')
param adminPasswordHash string = ''

@secure()
@description('HMAC secret signing fallback admin sessions. Required together with adminUsername.')
param adminSessionSecret string = ''

var suffix = take(uniqueString(subscription().id, resourceGroup().id, location), 6)
var storageName = 'st${take(replace(namePrefix, '-', ''), 10)}${suffix}'
var cosmosName = 'cosmos-${namePrefix}-${suffix}'
var keyVaultName = 'kv-${take(namePrefix, 12)}-${suffix}'
var logName = 'log-${namePrefix}-${suffix}'
var appInsightsName = 'appi-${namePrefix}-${suffix}'
var planName = 'plan-${namePrefix}-${suffix}'
var functionName = 'func-${namePrefix}-${suffix}'
var environmentName = 'cae-${namePrefix}-${suffix}'
var syncJobName = 'qzone-sync'
var authJobName = 'qzone-auth'
var importJobName = 'content-import'
var publishJobName = 'content-publish'
var mediaContainerName = 'media'
var privateContainerName = 'private'
var searchName = 'search-${namePrefix}-${suffix}'
var searchIndexName = 'bifrost-content'

resource storage 'Microsoft.Storage/storageAccounts@2024-01-01' = {
  name: storageName
  location: location
  sku: {
    name: 'Standard_LRS'
  }
  kind: 'StorageV2'
  properties: {
    allowBlobPublicAccess: true
    allowSharedKeyAccess: true
    minimumTlsVersion: 'TLS1_2'
    supportsHttpsTrafficOnly: true
  }
}

resource blobService 'Microsoft.Storage/storageAccounts/blobServices@2024-01-01' = {
  parent: storage
  name: 'default'
}

resource mediaContainer 'Microsoft.Storage/storageAccounts/blobServices/containers@2024-01-01' = {
  parent: blobService
  name: mediaContainerName
  properties: {
    publicAccess: 'Blob'
  }
}

resource privateContainer 'Microsoft.Storage/storageAccounts/blobServices/containers@2024-01-01' = {
  parent: blobService
  name: privateContainerName
  properties: {
    publicAccess: 'None'
  }
}

resource cosmos 'Microsoft.DocumentDB/databaseAccounts@2024-11-15' = {
  name: cosmosName
  location: location
  kind: 'GlobalDocumentDB'
  properties: {
    databaseAccountOfferType: 'Standard'
    enableFreeTier: true
    enableAutomaticFailover: false
    consistencyPolicy: {
      defaultConsistencyLevel: 'Session'
    }
    locations: [
      {
        locationName: location
        failoverPriority: 0
        isZoneRedundant: false
      }
    ]
  }
}

resource database 'Microsoft.DocumentDB/databaseAccounts/sqlDatabases@2024-11-15' = {
  parent: cosmos
  name: 'bifrost'
  properties: {
    resource: {
      id: 'bifrost'
    }
    options: {
      throughput: 1000
    }
  }
}

resource commentsContainer 'Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers@2024-11-15' = {
  parent: database
  name: 'comments'
  properties: {
    resource: {
      id: 'comments'
      // 以 entryId 归属：内容改网址后评论不会丢
      partitionKey: {
        paths: ['/entryId']
        kind: 'Hash'
      }
      indexingPolicy: {
        indexingMode: 'consistent'
        automatic: true
        includedPaths: [
          { path: '/*' }
        ]
        excludedPaths: [
          { path: '/content/?' }
        ]
      }
    }
  }
}

resource stateContainer 'Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers@2024-11-15' = {
  parent: database
  name: 'state'
  properties: {
    resource: {
      id: 'state'
      partitionKey: {
        paths: ['/partitionKey']
        kind: 'Hash'
      }
      indexingPolicy: {
        indexingMode: 'consistent'
        automatic: true
        includedPaths: [
          { path: '/*' }
        ]
        excludedPaths: []
      }
    }
  }
}

resource rateLimitsContainer 'Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers@2024-11-15' = {
  parent: database
  name: 'rate-limits'
  properties: {
    resource: {
      id: 'rate-limits'
      partitionKey: {
        paths: ['/key']
        kind: 'Hash'
      }
      indexingPolicy: {
        indexingMode: 'consistent'
        automatic: true
        includedPaths: [
          { path: '/*' }
        ]
        excludedPaths: []
      }
      defaultTtl: 86400
    }
  }
}

// ---------- 内容侧容器（见 docs/design/10-data-design.md 容器清单）----------
// 注意：正文 Markdown 与渲染 HTML 只用于展示，不参与查询，因此排除出索引。

resource contentArticlesContainer 'Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers@2024-11-15' = {
  parent: database
  name: 'content-articles'
  properties: {
    resource: {
      id: 'content-articles'
      partitionKey: {
        paths: ['/entryId']
        kind: 'Hash'
      }
      // 同一分区内放条目元数据、正文与历史版本，打开一篇只读一个分区
      indexingPolicy: {
        indexingMode: 'consistent'
        automatic: true
        includedPaths: [
          { path: '/*' }
        ]
        excludedPaths: [
          { path: '/markdown/?' }
          { path: '/html/?' }
          { path: '/text/?' }
        ]
      }
    }
  }
}

resource contentMomentsContainer 'Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers@2024-11-15' = {
  parent: database
  name: 'content-moments'
  properties: {
    resource: {
      id: 'content-moments'
      // 动态按发布月份分桶：翻最近只碰少数分区
      partitionKey: {
        paths: ['/month']
        kind: 'Hash'
      }
      indexingPolicy: {
        indexingMode: 'consistent'
        automatic: true
        includedPaths: [
          { path: '/*' }
        ]
        excludedPaths: [
          { path: '/html/?' }
          { path: '/text/?' }
        ]
      }
    }
  }
}

resource taxonomyContainer 'Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers@2024-11-15' = {
  parent: database
  name: 'taxonomy'
  properties: {
    resource: {
      id: 'taxonomy'
      partitionKey: {
        paths: ['/kind']
        kind: 'Hash'
      }
      indexingPolicy: {
        indexingMode: 'consistent'
        automatic: true
        includedPaths: [
          { path: '/*' }
        ]
        excludedPaths: []
      }
    }
  }
}

resource assetsContainer 'Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers@2024-11-15' = {
  parent: database
  name: 'assets'
  properties: {
    resource: {
      id: 'assets'
      partitionKey: {
        paths: ['/assetId']
        kind: 'Hash'
      }
      indexingPolicy: {
        indexingMode: 'consistent'
        automatic: true
        includedPaths: [
          { path: '/*' }
        ]
        excludedPaths: []
      }
    }
  }
}

resource routesContainer 'Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers@2024-11-15' = {
  parent: database
  name: 'routes'
  properties: {
    resource: {
      id: 'routes'
      // 分区键是路径本身；文档 id 不含路径，因为 Cosmos 的 id 不允许出现斜杠
      partitionKey: {
        paths: ['/path']
        kind: 'Hash'
      }
      indexingPolicy: {
        indexingMode: 'consistent'
        automatic: true
        includedPaths: [
          { path: '/*' }
        ]
        excludedPaths: []
      }
    }
  }
}

resource signalsContainer 'Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers@2024-11-15' = {
  parent: database
  name: 'signals'
  properties: {
    resource: {
      id: 'signals'
      partitionKey: {
        paths: ['/entryId']
        kind: 'Hash'
      }
      indexingPolicy: {
        indexingMode: 'consistent'
        automatic: true
        includedPaths: [
          { path: '/*' }
        ]
        excludedPaths: []
      }
      // 容器本身不过期；阅读去重文档自带 180 天 TTL
      defaultTtl: -1
    }
  }
}

resource searchDocsContainer 'Microsoft.DocumentDB/databaseAccounts/sqlDatabases/containers@2024-11-15' = {
  parent: database
  name: 'search-docs'
  properties: {
    resource: {
      id: 'search-docs'
      // 检索投影：唯一数据源，供 AI Search 索引器读取
      partitionKey: {
        paths: ['/entryId']
        kind: 'Hash'
      }
      indexingPolicy: {
        indexingMode: 'consistent'
        automatic: true
        includedPaths: [
          { path: '/*' }
        ]
        excludedPaths: []
      }
    }
  }
}

// 检索服务：免费层起步；索引定义见 tools/lib/search-config.mjs
resource search 'Microsoft.Search/searchServices@2023-11-01' = {
  name: searchName
  location: location
  sku: {
    name: 'free'
  }
  properties: {
    replicaCount: 1
    partitionCount: 1
    hostingMode: 'default'
    // 函数应用与发布任务都用 DefaultAzureCredential 访问索引；
    // 必须显式声明 Entra ID 鉴权，否则 ARM 更新会把服务退回 apiKeyOnly。
    authOptions: {
      aadOrApiKey: {
        aadAuthFailureMode: 'http401WithBearerChallenge'
      }
    }
  }
}

resource keyVault 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: keyVaultName
  location: location
  properties: {
    tenantId: tenant().tenantId
    sku: {
      family: 'A'
      name: 'standard'
    }
    enableRbacAuthorization: true
    enableSoftDelete: true
    softDeleteRetentionInDays: 90
    enablePurgeProtection: true
    publicNetworkAccess: 'Enabled'
  }
}

resource githubKeySecret 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: keyVault
  name: 'github-app-private-key'
  properties: {
    value: githubAppPrivateKey
  }
}

resource hashSaltSecret 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = {
  parent: keyVault
  name: 'interaction-hash-salt'
  properties: {
    value: hashSalt
  }
}

// 账密登录凭据：参数留空时整体不启用，保持与既有 Entra 通道互不影响。
resource adminPasswordHashSecret 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = if (!empty(adminPasswordHash)) {
  parent: keyVault
  name: 'admin-password-hash'
  properties: {
    value: adminPasswordHash
  }
}

resource adminSessionKeySecret 'Microsoft.KeyVault/vaults/secrets@2023-07-01' = if (!empty(adminSessionSecret)) {
  parent: keyVault
  name: 'admin-session-secret'
  properties: {
    value: adminSessionSecret
  }
}

resource logAnalytics 'Microsoft.OperationalInsights/workspaces@2023-09-01' = {
  name: logName
  location: location
  properties: {
    sku: {
      name: 'PerGB2018'
    }
    retentionInDays: 30
  }
}

resource applicationInsights 'Microsoft.Insights/components@2020-02-02' = {
  name: appInsightsName
  location: location
  kind: 'web'
  properties: {
    Application_Type: 'web'
    WorkspaceResourceId: logAnalytics.id
  }
}

resource functionPlan 'Microsoft.Web/serverfarms@2023-12-01' = {
  name: planName
  location: location
  sku: {
    name: 'Y1'
    tier: 'Dynamic'
  }
  properties: {
    reserved: true
  }
}

resource functionApp 'Microsoft.Web/sites@2023-12-01' = {
  name: functionName
  location: location
  kind: 'functionapp,linux'
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    serverFarmId: functionPlan.id
    httpsOnly: true
    publicNetworkAccess: 'Enabled'
    clientAffinityEnabled: false
    siteConfig: {
      linuxFxVersion: 'NODE|22'
      alwaysOn: false
      ftpsState: 'Disabled'
      minTlsVersion: '1.2'
      cors: {
        allowedOrigins: allowedOrigins
      }
      appSettings: [
        {
          name: 'AzureWebJobsStorage'
          value: concat(
            'DefaultEndpointsProtocol=https;AccountName=',
            storage.name,
            ';AccountKey=',
            storage.listKeys().keys[0].value,
            ';EndpointSuffix=',
            environment().suffixes.storage
          )
        }
        {
          name: 'WEBSITE_CONTENTAZUREFILECONNECTIONSTRING'
          value: concat(
            'DefaultEndpointsProtocol=https;AccountName=',
            storage.name,
            ';AccountKey=',
            storage.listKeys().keys[0].value,
            ';EndpointSuffix=',
            environment().suffixes.storage
          )
        }
        {
          name: 'WEBSITE_CONTENTSHARE'
          value: toLower(functionName)
        }
        {
          name: 'FUNCTIONS_EXTENSION_VERSION'
          value: '~4'
        }
        {
          name: 'FUNCTIONS_WORKER_RUNTIME'
          value: 'node'
        }
        {
          name: 'WEBSITE_NODE_DEFAULT_VERSION'
          value: '~22'
        }
        {
          name: 'SCM_DO_BUILD_DURING_DEPLOYMENT'
          value: 'true'
        }
        {
          name: 'APPLICATIONINSIGHTS_CONNECTION_STRING'
          value: applicationInsights.properties.ConnectionString
        }
        {
          name: 'COSMOS_ENDPOINT'
          value: cosmos.properties.documentEndpoint
        }
        {
          name: 'COSMOS_DATABASE'
          value: 'bifrost'
        }
        {
          name: 'SEARCH_ENDPOINT'
          value: 'https://${searchName}.search.windows.net'
        }
        {
          name: 'SEARCH_INDEX'
          value: searchIndexName
        }
        {
          name: 'BLOB_ACCOUNT_URL'
          value: storage.properties.primaryEndpoints.blob
        }
        {
          name: 'MEDIA_CONTAINER'
          value: mediaContainerName
        }
        {
          name: 'PRIVATE_CONTAINER'
          value: privateContainerName
        }
        {
          name: 'KEY_VAULT_URI'
          value: keyVault.properties.vaultUri
        }
        {
          name: 'HASH_SALT'
          value: '@Microsoft.KeyVault(SecretUri=${keyVault.properties.vaultUri}secrets/interaction-hash-salt/)'
        }
        {
          name: 'ALLOWED_ORIGINS'
          value: join(allowedOrigins, ',')
        }
        {
          name: 'ENTRA_TENANT_ID'
          value: entraTenantId
        }
        {
          name: 'ENTRA_CLIENT_ID'
          value: entraClientId
        }
        {
          name: 'ENTRA_API_AUDIENCE'
          value: entraApiAudience
        }
        {
          name: 'ADMIN_OBJECT_IDS'
          value: join(adminObjectIds, ',')
        }
        ...(empty(adminUsername) ? [] : [
          {
            name: 'ADMIN_USERNAME'
            value: adminUsername
          }
        ])
        ...(empty(adminPasswordHash) ? [] : [
          {
            name: 'ADMIN_PASSWORD_HASH'
            value: '@Microsoft.KeyVault(SecretUri=${keyVault.properties.vaultUri}secrets/admin-password-hash/)'
          }
        ])
        ...(empty(adminSessionSecret) ? [] : [
          {
            name: 'ADMIN_SESSION_SECRET'
            value: '@Microsoft.KeyVault(SecretUri=${keyVault.properties.vaultUri}secrets/admin-session-secret/)'
          }
        ])
        {
          name: 'INTERACTIONS_ENABLED'
          value: 'true'
        }
        {
          name: 'SUBSCRIPTION_ID'
          value: subscription().subscriptionId
        }
        {
          name: 'RESOURCE_GROUP'
          value: resourceGroup().name
        }
        {
          name: 'SYNC_AUTH_JOB_NAME'
          value: authJobName
        }
        {
          name: 'SYNC_JOB_NAME'
          value: syncJobName
        }
        {
          name: 'IMPORT_JOB_NAME'
          value: importJobName
        }
        {
          name: 'PUBLISH_JOB_NAME'
          value: publishJobName
        }
        {
          name: 'MAX_UPLOAD_BYTES'
          value: string(100 * 1024 * 1024)
        }
      ]
    }
  }
}

resource containerEnvironment 'Microsoft.App/managedEnvironments@2026-03-02-preview' = {
  name: environmentName
  location: location
  properties: {
    environmentMode: 'WorkloadProfiles'
    workloadProfiles: [
      {
        name: 'Consumption'
        workloadProfileType: 'Consumption'
      }
    ]
    appLogsConfiguration: {
      destination: 'log-analytics'
      logAnalyticsConfiguration: {
        customerId: logAnalytics.properties.customerId
        sharedKey: logAnalytics.listKeys().primarySharedKey
      }
    }
  }
}

var syncEnvironment = [
  { name: 'COSMOS_ENDPOINT', value: cosmos.properties.documentEndpoint }
  { name: 'COSMOS_DATABASE', value: 'bifrost' }
  { name: 'BLOB_ACCOUNT_URL', value: storage.properties.primaryEndpoints.blob }
  { name: 'MEDIA_CONTAINER', value: mediaContainerName }
  { name: 'PRIVATE_CONTAINER', value: privateContainerName }
  { name: 'KEY_VAULT_URI', value: keyVault.properties.vaultUri }
  { name: 'GITHUB_APP_PRIVATE_KEY_SECRET_NAME', value: 'github-app-private-key' }
  { name: 'GITHUB_APP_ID', value: githubAppId }
  { name: 'GITHUB_APP_INSTALLATION_ID', value: githubAppInstallationId }
  { name: 'GITHUB_REPOSITORY', value: githubRepository }
  { name: 'GITHUB_BRANCH', value: 'main' }
  { name: 'CONTENT_COMMIT_PREFIX', value: 'content-src/imported/qq' }
  { name: 'QZONE_STATE_PARTITION', value: 'sync' }
  { name: 'PLAYWRIGHT_HEADLESS', value: 'true' }
]

resource authJob 'Microsoft.App/jobs@2024-03-01' = {
  name: authJobName
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    environmentId: containerEnvironment.id
    configuration: {
      triggerType: 'Manual'
      replicaTimeout: 1800
      replicaRetryLimit: 1
      manualTriggerConfig: {
        parallelism: 1
        replicaCompletionCount: 1
      }
    }
    template: {
      containers: [
        {
          name: authJobName
          image: syncImage
          env: concat(syncEnvironment, [
            { name: 'QZONE_MODE', value: 'auth' }
          ])
          resources: {
            cpu: json('1.0')
            memory: '2Gi'
          }
        }
      ]
    }
  }
}

resource syncJob 'Microsoft.App/jobs@2024-03-01' = {
  name: syncJobName
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    environmentId: containerEnvironment.id
    configuration: {
      triggerType: 'Schedule'
      replicaTimeout: 3600
      replicaRetryLimit: 1
      scheduleTriggerConfig: {
        cronExpression: '0 18 * * *'
        parallelism: 1
        replicaCompletionCount: 1
      }
    }
    template: {
      containers: [
        {
          name: syncJobName
          image: syncImage
          env: concat(syncEnvironment, [
            { name: 'QZONE_MODE', value: 'sync' }
          ])
          resources: {
            cpu: json('1.0')
            memory: '2Gi'
          }
        }
      ]
    }
  }
}

// 内容导入与发布任务：与 QQ 同步共用同一镜像，靠 command 覆盖选择入口脚本。
var contentEnvironment = concat(syncEnvironment, [
  { name: 'SEARCH_ENDPOINT', value: 'https://${searchName}.search.windows.net' }
  { name: 'SEARCH_INDEX', value: 'bifrost-content' }
  { name: 'SITE_URL', value: 'https://cpower-2ng.github.io' }
])

resource importJob 'Microsoft.App/jobs@2024-03-01' = {
  name: importJobName
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    environmentId: containerEnvironment.id
    configuration: {
      triggerType: 'Manual'
      replicaTimeout: 3600
      replicaRetryLimit: 1
      manualTriggerConfig: {
        parallelism: 1
        replicaCompletionCount: 1
      }
    }
    template: {
      containers: [
        {
          name: importJobName
          image: syncImage
          command: [
            'node'
            'tools/cloud-import.mjs'
          ]
          env: contentEnvironment
          resources: {
            cpu: json('1.0')
            memory: '2Gi'
          }
        }
      ]
    }
  }
}

resource publishJob 'Microsoft.App/jobs@2024-03-01' = {
  name: publishJobName
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    environmentId: containerEnvironment.id
    configuration: {
      // 每天北京 02:30（UTC 18:30）自动物化：紧跟 02:00 的定时 QQ 同步，
      // 同步什么就上线什么；手动「发布站点」仍走同一条路。
      triggerType: 'Schedule'
      replicaTimeout: 3600
      replicaRetryLimit: 1
      scheduleTriggerConfig: {
        cronExpression: '30 18 * * *'
        parallelism: 1
        replicaCompletionCount: 1
      }
    }
    template: {
      containers: [
        {
          name: publishJobName
          image: syncImage
          command: [
            'node'
            'tools/cloud-publish.mjs'
          ]
          env: contentEnvironment
          resources: {
            cpu: json('1.0')
            memory: '2Gi'
          }
        }
      ]
    }
  }
}

resource functionImportJobOperator 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(importJob.id, functionApp.id, 'container-apps-job-contributor')
  scope: importJob
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'b24988ac-6180-42a0-ab88-20f7382dd24c')
    principalId: functionApp.identity.principalId
    principalType: 'ServicePrincipal'
  }
}

resource functionPublishJobOperator 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(publishJob.id, functionApp.id, 'container-apps-job-contributor')
  scope: publishJob
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'b24988ac-6180-42a0-ab88-20f7382dd24c')
    principalId: functionApp.identity.principalId
    principalType: 'ServicePrincipal'
  }
}

resource functionAuthJobOperator 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(authJob.id, functionApp.id, 'container-apps-job-contributor')
  scope: authJob
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'b24988ac-6180-42a0-ab88-20f7382dd24c')
    principalId: functionApp.identity.principalId
    principalType: 'ServicePrincipal'
  }
}

resource functionSyncJobOperator 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(syncJob.id, functionApp.id, 'container-apps-job-contributor')
  scope: syncJob
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'b24988ac-6180-42a0-ab88-20f7382dd24c')
    principalId: functionApp.identity.principalId
    principalType: 'ServicePrincipal'
  }
}

resource cosmosDataContributorRoleId 'Microsoft.DocumentDB/databaseAccounts/sqlRoleDefinitions@2024-11-15' existing = {
  parent: cosmos
  name: '00000000-0000-0000-0000-000000000002'
}

resource functionCosmosRole 'Microsoft.DocumentDB/databaseAccounts/sqlRoleAssignments@2024-11-15' = {
  parent: cosmos
  name: guid(cosmos.id, functionApp.id, cosmosDataContributorRoleId.id)
  properties: {
    roleDefinitionId: cosmosDataContributorRoleId.id
    principalId: functionApp.identity.principalId
    scope: cosmos.id
  }
}

resource authCosmosRole 'Microsoft.DocumentDB/databaseAccounts/sqlRoleAssignments@2024-11-15' = {
  parent: cosmos
  name: guid(cosmos.id, authJob.id, cosmosDataContributorRoleId.id)
  properties: {
    roleDefinitionId: cosmosDataContributorRoleId.id
    principalId: authJob.identity.principalId
    scope: cosmos.id
  }
}

resource syncCosmosRole 'Microsoft.DocumentDB/databaseAccounts/sqlRoleAssignments@2024-11-15' = {
  parent: cosmos
  name: guid(cosmos.id, syncJob.id, cosmosDataContributorRoleId.id)
  properties: {
    roleDefinitionId: cosmosDataContributorRoleId.id
    principalId: syncJob.identity.principalId
    scope: cosmos.id
  }
}

resource functionBlobRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(storage.id, functionApp.id, 'storage-blob-data-contributor')
  scope: storage
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'ba92f5b4-2d11-453d-a403-e96b0029c9fe')
    principalId: functionApp.identity.principalId
    principalType: 'ServicePrincipal'
  }
}

resource functionBlobDelegatorRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(storage.id, functionApp.id, 'storage-blob-delegator')
  scope: storage
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'db58b8e5-c6ad-4a2a-8342-4190687cbf4a')
    principalId: functionApp.identity.principalId
    principalType: 'ServicePrincipal'
  }
}

resource syncBlobRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(storage.id, syncJob.id, 'storage-blob-data-contributor')
  scope: storage
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'ba92f5b4-2d11-453d-a403-e96b0029c9fe')
    principalId: syncJob.identity.principalId
    principalType: 'ServicePrincipal'
  }
}

resource authBlobRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(storage.id, authJob.id, 'storage-blob-data-contributor')
  scope: storage
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'ba92f5b4-2d11-453d-a403-e96b0029c9fe')
    principalId: authJob.identity.principalId
    principalType: 'ServicePrincipal'
  }
}

resource functionKeyVaultRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(keyVault.id, functionApp.id, 'key-vault-secrets-user')
  scope: keyVault
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '4633458b-17de-408a-b874-0445c86b69e6')
    principalId: functionApp.identity.principalId
    principalType: 'ServicePrincipal'
  }
}

resource syncKeyVaultRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(keyVault.id, syncJob.id, 'key-vault-secrets-user')
  scope: keyVault
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '4633458b-17de-408a-b874-0445c86b69e6')
    principalId: syncJob.identity.principalId
    principalType: 'ServicePrincipal'
  }
}

resource authKeyVaultRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(keyVault.id, authJob.id, 'key-vault-secrets-user')
  scope: keyVault
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '4633458b-17de-408a-b874-0445c86b69e6')
    principalId: authJob.identity.principalId
    principalType: 'ServicePrincipal'
  }
}

// 函数应用只读检索索引
resource functionSearchRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(search.id, functionApp.id, 'search-index-data-reader')
  scope: search
  properties: {
    // Search Index Data Reader
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '1407120a-92aa-4202-b7e9-c0e197c71c8f')
    principalId: functionApp.identity.principalId
    principalType: 'ServicePrincipal'
  }
}

resource syncKeyVaultOfficer 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(keyVault.id, syncJob.id, 'key-vault-secrets-officer')
  scope: keyVault
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'b86a8fe4-44ce-4948-aee5-eccb2c155cd7')
    principalId: syncJob.identity.principalId
    principalType: 'ServicePrincipal'
  }
}

resource authKeyVaultOfficer 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(keyVault.id, authJob.id, 'key-vault-secrets-officer')
  scope: keyVault
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'b86a8fe4-44ce-4948-aee5-eccb2c155cd7')
    principalId: authJob.identity.principalId
    principalType: 'ServicePrincipal'
  }
}

resource importCosmosRole 'Microsoft.DocumentDB/databaseAccounts/sqlRoleAssignments@2024-11-15' = {
  parent: cosmos
  name: guid(cosmos.id, importJob.id, cosmosDataContributorRoleId.id)
  properties: {
    roleDefinitionId: cosmosDataContributorRoleId.id
    principalId: importJob.identity.principalId
    scope: cosmos.id
  }
}

resource publishCosmosRole 'Microsoft.DocumentDB/databaseAccounts/sqlRoleAssignments@2024-11-15' = {
  parent: cosmos
  name: guid(cosmos.id, publishJob.id, cosmosDataContributorRoleId.id)
  properties: {
    roleDefinitionId: cosmosDataContributorRoleId.id
    principalId: publishJob.identity.principalId
    scope: cosmos.id
  }
}

resource importBlobRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(storage.id, importJob.id, 'storage-blob-data-contributor')
  scope: storage
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', 'ba92f5b4-2d11-453d-a403-e96b0029c9fe')
    principalId: importJob.identity.principalId
    principalType: 'ServicePrincipal'
  }
}

resource publishKeyVaultRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(keyVault.id, publishJob.id, 'key-vault-secrets-user')
  scope: keyVault
  properties: {
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '4633458b-17de-408a-b874-0445c86b69e6')
    principalId: publishJob.identity.principalId
    principalType: 'ServicePrincipal'
  }
}

// 发布任务要把投影推送到 AI Search，需要索引写入权限。
resource publishSearchRole 'Microsoft.Authorization/roleAssignments@2022-04-01' = {
  name: guid(search.id, publishJob.id, 'search-index-data-contributor')
  scope: search
  properties: {
    // Search Index Data Contributor
    roleDefinitionId: subscriptionResourceId('Microsoft.Authorization/roleDefinitions', '8ebe5a00-799e-43f5-93ac-243d3dce84a7')
    principalId: publishJob.identity.principalId
    principalType: 'ServicePrincipal'
  }
}

resource monthlyBudget 'Microsoft.Consumption/budgets@2023-11-01' = if (length(budgetContactEmails) > 0) {
  name: 'bifrost-monthly-budget'
  properties: {
    category: 'Cost'
    amount: 20
    timeGrain: 'Monthly'
    timePeriod: {
      startDate: budgetStartDate
      endDate: '2036-01-01T00:00:00Z'
    }
    notifications: {
      fiftyPercent: {
        enabled: true
        operator: 'GreaterThanOrEqualTo'
        threshold: 50
        contactEmails: budgetContactEmails
        thresholdType: 'Actual'
      }
      eightyPercent: {
        enabled: true
        operator: 'GreaterThanOrEqualTo'
        threshold: 80
        contactEmails: budgetContactEmails
        thresholdType: 'Actual'
      }
      oneHundredPercent: {
        enabled: true
        operator: 'GreaterThanOrEqualTo'
        threshold: 100
        contactEmails: budgetContactEmails
        thresholdType: 'Actual'
      }
    }
  }
}

output functionAppName string = functionApp.name
output functionAppHostName string = functionApp.properties.defaultHostName
output cosmosEndpoint string = cosmos.properties.documentEndpoint
output blobEndpoint string = storage.properties.primaryEndpoints.blob
output keyVaultUri string = keyVault.properties.vaultUri
output syncJobName string = syncJob.name
output authJobName string = authJob.name
